### PR TITLE
added getVirtualReportSuiteComponents function

### PR DESCRIPTION
**Pull request by loldenburg**
getVirtualReportSuiteComponents gets the components of a VRS into a dataframe with columns "componentId", "componentType" and "curatedName. For this, the Report Suite must have Component Curation enabled.

### CODE REVIEW

**Comment by pitchmuc** [comment]
Thanks @loldenburg 
I have seen that there are some additional files into your git pull request. (in folder .idea)
Should I remove them ? 

It seems that the 2 pull requests are actually the same one as you are fixing the save parameter in this one. 
I guess you are fine with me moving forward with only one PR and dropping the other one as it has been included here.

**Comment by loldenburg** [comment]
@pitchmuc yeah i am sorry for that. I suck at Git operations still, but learned more today. You can discard this Pull Request https://github.com/pitchmuc/adobe_analytics_api_2.0/pull/22 and simply merge this one.

The .idea files were probably generated by PyCharm automatically, you can reject them as well. Forgot to create a .gitignore file so that they are ignored.
Thanks!

**Comment by pitchmuc** [comment]
No worry, I am not the best either. 
I am a marketing guy , first of all, just learning by doing :) 
Just wanted to inform before doing it. 

Thanks for the fix.

**Comment by pitchmuc** [comment]
After cleaning it (docstring) and I also improve stability by returning empty dataframe when there is no curatedComponents. 
I have merged the proposal. 
Let me know if it works as expected. 
I will push to pypi afterwards.

**Comment by loldenburg** [comment]
@pitchmuc thanks, I checked, it works! 👍 
I think in the case of an empty frame, some kind of info/error message could be logged too, but that can be added later.

**Pull request merged**
