### PR TITLE
Allow supplying absolute path to the private key

### LINKED ISSUE #19: Unable to supply absolute path to the private key
Due to the checks applied in the `retrieveToken` and `importConfigFile` functions it's currently not possible to supply a configuration with an absolute path to the private key.

While generally, it may be not a biggie, in some environments it is a critical issue. In our case, we're not able to determine the folder from which the app is going to be started, so it's not possible to provide a normal relative path to the key. In such a scenario, we'd like to provide a full path to the key instead.

### PR DESCRIPTION
**Pull request by xSAVIKx**
This PR fixes #19.

I've dropped the `startsWith("/"` checks and improved docs a bit.

### CODE REVIEW

**Comment by xSAVIKx** [comment]
@pitchmuc PTAL.

**Comment by pitchmuc** [comment]
Hello and thanks for the Pull request. 
I am testing it now and the error I was trying to avoid is popping up again : 
image

In my config file, I am using this notation : 
```JSON
{
    "org_id": "ED48F97C5922D40C00@AdobeOrg",
    "api_key": "d2ef4b231cea4cf29d91b10052",
    "tech_id": "3155ED511C70AE8@techacct.adobe.com",
    "secret": "**********************",
    "pathToKey": "/config/private.key"
}
```

This kind of notation could be used and I wanted my function to work in that case. 
In order to avoid that issue, I was doing my startswith() but it seems that it prevents you from using full path.

Normally, when entering the full path, it should starts with something like "C://". (so my startswith should avoid messing with it). 
Is it different on your environment ? 

I need to think of a way to make both work.

**Comment by xSAVIKx** [comment]
That's some new path notation for me.

In *NIX systems, an absolute path starts with a `/` and a relative one starts with a `./`.
In Windows, an absolute path starts with `C:\\` as you've mentioned, while a relative remains the same `.\`.

I'm not sure why you're avoiding using `C:\\`-like paths, but for *NIX systems, the current `startswith()` workaround breaks the usage of absolute paths completely.

From my perspective, the library should support commonly-used standards and can support non-standard notations if they do not break compatibility.

I'd be glad to help you out here if there's smth else I can do.

**Comment by pitchmuc** [comment]
OK. I am not having ton of experience on NIX system, this is interesting. Thanks for your explanation. 

I am trying to be flexible so you can use both notation, independently of your current system. 
I tried to upload a new version of the import logic in your branch. 

The main idea is to check if the file can be accessed before applying this startswith(). 
By checking if file exist, it may solve your issue without breaking my code. 

Main logic here:

```python
test_path = _Path(path).exists()
    if test_path == False:
        if path.startswith('/'):
            path = "."+path
    with open(_Path(path), 'r') as file:
        ....
```

Let me know if this works for you.

**Comment by xSAVIKx** [comment]
@pitchmuc PTAL again.

I've added a reusable part that checks the presence of the file using the supplied path and uses the file if it is available, otherwise tries to convert the absolute path to a relative one and tries it out.

I've also added the fail-fast approach with exceptions if config/private key files are not available.

**Comment by xSAVIKx** [comment]
@pitchmuc I've back merged your latest changes. It'd be great if you can check it out.

Please let me know if there's anything else you'd like me to do/change before merging the PR.

**Comment by pitchmuc** [comment]
Hello @xSAVIKx , 
I checked the commit, thank for the function provided. It makes it cleaner. 
I will merge the proposed changes. 
We are not in sync with the master anymore as I provided a new version with VirtualReport capability for @loldenburg. I will take care of merging the changes. 
You proposed suggestion will be part of the next release on pypi.  
Thanks a lot !

**Comment by Ryuno-Ki** [comment]
@pitchmuc Perhaps worth to use https://docs.python.org/3/library/os.html#os.sep in the future.

**Pull request merged**
