### PR TITLE
Add dedicated API for programmatic config

### PR DESCRIPTION
**Pull request by xSAVIKx**
This PR addresses #26 by providing a dedicated direct way to configure the library programmatically.

### CODE REVIEW

**Comment by xSAVIKx** [comment]
@pitchmuc @loldenburg PTAL at the changes.

**Comment by loldenburg** [comment]
@xSAVIKx Thanks a ton! @pitchmuc This should solve https://github.com/pitchmuc/adobe_analytics_api_2.0/issues/26
In future updates, I think it is important that the library does not expect (only) a config FILE, but that there is also a way to configure the Credentials with a function and parameter input.

**Comment by pitchmuc** [comment]
Thanks @xSAVIKx for the new API and a bit of cleaning on the different methods used. 

I wanted to push back the changes I made to this PR for review but I couldn't, neither could I created a new branch from this PR.
So I directly added it on the master.  
My lack of Git knoweldge may have been the main issue here...
 
I have updated the documentation for [authenticating without config file](https://github.com/pitchmuc/adobe_analytics_api_2.0/blob/master/docs/authenticating_without_config_json.md) based on the new methods provided.
@loldenburg, could you check if that is the way you are doing it ? 
I will add the Tags endpoint before doing a Pypi release.

**Comment by loldenburg** [comment]
Thanks to both of you, great stuff! I will test as soon as I can, can take
a couple of days though.

**Comment by loldenburg** [comment]
@pitchmuc thx again, I verified the update works, the description seems fine to me!

**Pull request merged**
