### PR TITLE
Allow passing private key to configure method

### PR DESCRIPTION
**Pull request by omgMath**
In our use case, we want to avoid file system access. Therefore, we need a way to pass the private key to the `configure` method instead of reading it from the file system.

This pull request handles that.

### CODE REVIEW

**Comment by pitchmuc** [comment]
Hello
Quickly reviewing the PR, I am trying to rephrase the requirement just to be sure. 
You want to pass the private key as a variable, not through a file read method. Is that correct ? 

That is an interesting use-case, I would like to keep future versions of the library backward compatible and the PR doesn't seem to do that. (just a quick review)

I'll look how I can do that from your suggestion.
So this will come but probably not this way.

**Comment by omgMath** [comment]
>  You want to pass the private key as a variable, not through a file read method. Is that correct ?

Yes, exactly.

> That is an interesting use-case, I would like to keep future versions of the library backward compatible and the PR doesn't seem to do that. (just a quick review)

Unless I missed something, everything should be backward-compatible. The `configure` method takes an additional (optional!) parameter. If not provided everything should work as usual.

**Comment by pitchmuc** [comment]
My bad @omgMath 
I looked at it more seriously today and you just cleaned the code (thanks!) and added the proxy method get_private_key_from_config
I review it and tested and looks great ! 
This will come this week as pypi release (0.1.7), I'll add some stuff in the doc so people know that this option exist.(I didn't document the configure method yet).
Any twitter account I can give credit to for this release ?

**Comment by omgMath** [comment]
>This will come this week as pypi release (0.1.7), I'll add some stuff in the doc so people know that this option exist.(I didn't document the configure method yet).

The configure method is already documented [here](https://github.com/pitchmuc/adobe_analytics_api_2.0/blob/master/docs/authenticating_without_config_json.md), which is also extended with this pull request.

Thank you! Looking forward to the new version :+1:

**Comment by pitchmuc** [comment]
I even forgot I wrote that part :D 
What I meant is that, I will also include reference to it on the [get-started ](https://github.com/pitchmuc/adobe_analytics_api_2.0/blob/master/docs/getting_started.md)page.

**Comment by omgMath** [comment]
> What I meant is that, I will also include reference to it on the get-started page.

Sounds good!

>  Any twitter account I can give credit to for this release ?

Sorry, forgot to answer that question. But I don't have twitter account anyway. :smile: 
No need to give me credit, it was just a very very small contribution...

**Comment by pitchmuc** [comment]
There are no small contribution ;) 
Especially when you already created it for yourself. 
Sharing and making it available to everyone is always appreciated.

**Pull request merged**
