### PR TITLE
Improve dependencies handling

### PR DESCRIPTION
**Pull request by xSAVIKx**
In this PR I've dropped usage of the `modules.py` uber-dependency-management script in order to improve the reliability of the library.

Usage of such single-dependency files is usually error-prone and fewer benefits than potential dependency-resolution issues.

### CODE REVIEW

**Comment by xSAVIKx** [comment]
@pitchmuc PTAL at the changes.

I'm doing this PR as I'm not able to install the library locally anymore. I do advise to not use such scripts as `modules.py` for handling dependencies.

**Comment by loldenburg** [comment]
@pitchmuc these fixes are important as the latest update broke everything in the cloud (later it also got shaky locally). Thanks for trying with @xSAVIKx 's approach that does not require a modules.py file

**Comment by pitchmuc** [comment]
Hello guys, 

I am a bit confused here. 
The modules.py is in place for at least 3 releases. 
Could you send me the error that was showing ? 
The only major change on the last release is the new import config endpoint. 

How certain are we that it comes from modules.py ?  
It is a massive change that needs to be done in the different part of the code. 

I'll review the PR in the meanwhile.

**Comment by xSAVIKx** [comment]
@pitchmuc here's an example stack trace from the build:

```
/opt/python3.7/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-bzb1pdn8/aanalytics2/setup.py'"'"'; file='"'"'/tmp/pip-wheel-bzb1pdn8/aanalytics2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7l46sjdk\n cwd: /tmp/pip-wheel-bzb1pdn8/aanalytics2/\n Complete output (13 lines):\n Traceback (most recent call last):\n File "<string>", line 1, in <module>\n File "/tmp/pip-wheel-bzb1pdn8/aanalytics2/setup.py", line 3, in <module>\n from aanalytics2 import version\n File "/tmp/pip-wheel-bzb1pdn8/aanalytics2/aanalytics2/init.py", line 3, in <module>\n from .aanalytics2 import *\n File "/tmp/pip-wheel-bzb1pdn8/aanalytics2/aanalytics2/aanalytics2.py", line 6, in <module>\n from aanalytics2 import config, connector, modules\n File "/tmp/pip-wheel-bzb1pdn8/aanalytics2/aanalytics2/connector.py", line 1, in <module>\n from aanalytics2 import config, modules\n File "/tmp/pip-wheel-bzb1pdn8/aanalytics2/aanalytics2/modules.py", line 3, in <module>\n import jwt\n ModuleNotFoundError: No module named 'jwt'\n
```

It ends up in `modules.py` and it's `import jwt`.

**Comment by xSAVIKx** [comment]
Unfortunately, such things as `modules.py` may produce unexpected results in different build environments. For me, it was failing both in my local dev env (Windows PC) and in the cloud env on Linux servers.

**Comment by xSAVIKx** [comment]
The only **functional** change in the PR is in commits (b6035dc3086725fb4b720baed2c1992205cda4c7 and cf86500b78dd74b95327fee3aa9fcf40339fba9d, which are also covered by @loldenburg PR #30, he asked me to integrate his changes into mine PR).

All other changes are just cleanups and removal of `modules` usage.

**Comment by pitchmuc** [comment]
Thanks @xSAVIKx.
Seems related to pyJWT especially.
Crazy. works for me on any version. 
Isn't it an issue on the dependencies installation ? 

As you may have seen the "modules" is used a bit everywhere... so quite a lot of work to change everywhere.

**Comment by xSAVIKx** [comment]
I'd say it's an issue on the initialization process and it's quite hard to somehow experiment with it when all 3rdparty imports are in some other script (`modules.py`).

In the PR I already dropped the usage of `modules` completely. It's gone. Instead, it is a good practice to actually import all needed dependencies in the source code which requires them.

With the `modules.py` it was not clear which imports are really relevant for which scripts.

**Comment by pitchmuc** [comment]
Yep I understand that point (which library is used where is not easy to know). 
Cool if you drop that usage everywhere. Do you have a method to do that programmatically or did you review the whole code ? 
It is not a small task.

Did this solve your issue at the end ?

**Comment by xSAVIKx** [comment]
Yes, it solves the problem.

I do it with "usages" functionality of PyCharm. I just find all the usages and then fix one-by-one or in bulk.

**Comment by pitchmuc** [comment]
Thanks again @xSAVIKx I wouldn't think that I would be able to push that today. 
@loldenburg I will test today on my end before pushing on pypi (version 0.1.4 then)
This version also includes the getProjects and getProjects methods if you want to test ;)

**Pull request merged**
