### PR TITLE
Create authenticating_without_config_json.md

### PR DESCRIPTION
**Pull request by loldenburg**

### CODE REVIEW

**Comment by loldenburg** [comment]
@pitchmuc Took me a while to figure this out. It would have helped me a lot, as I do not use Jupyter Notebooks because I run scripts in the Cloud and in a scheduled manner. There I cannot work with config.json files.

**Comment by pitchmuc** [comment]
Thanks a ton for the documentation. 
I will probably do a video on that soon to cover it in my examples.

**Comment by loldenburg** [comment]
Thanks. Actually I celebrated too early. We stumbled on some problem
related to the retrieveToken function also related to the file structure,
this time of the private key. My colleague Savik had to make its own branch
here
https://github.com/xSAVIKx/adobe_analytics_api_2.0/tree/drop-the-startswith-part

Maybe he also wrote to you.
The problem is that it is checked whether there is a preceding "/" in the
file name, and if so, a "." is prepended, which in our case led to a move
to a directory above the root directory (which is possible in the Cloud).
The solution he provided is to make it work only for me, but it may break
other things.

Anyway thanks a ton for your efforts!
Lukas



--
Lukas Oldenburg
dim28 GmbH
Grubenackerstr. 73
8052 Zürich
lukas.oldenburg@dim28.ch
+41 76 703 6883
CHE‑297.313.490 MWST

**Comment by pitchmuc** [comment]
Yes, I reviewed the change today from Savik today. 
It remove the check and unfortunately break a use-case I had this startwith for. 
I used to think that ".." is to go to parent folder and "." is to use for current directory... 
We started the discussion on another pull request.

**Pull request merged**
